MENU_MAIN = "menu:main"
MENU_ADD = "menu:add"
MENU_SEARCH = "menu:search"
MENU_LIST = "menu:list"
MENU_TOPICS = "menu:topics"
MENU_COLLECTIONS = "menu:collections"
MENU_IMPORT_EXPORT = "menu:import_export"
MENU_BACKUPS = "menu:backups"
MENU_STATS = "menu:stats"
MENU_HELP = "menu:help"
MENU_CANCEL_FLOW = "menu:cancel_flow"
MENU_TOPIC_CREATE = "menu:topic_create"

LIST_ALL = "list:all"
LIST_NEW = "list:new"
LIST_TO_READ = "list:to_read"
LIST_VERIFIED = "list:verified"

ADD_TOPIC_PREFIX = "add:topic:"
ENTRY_VIEW_PREFIX = "entry:view:"
ENTRY_STATUS_PREFIX = "entry:status:"
TOPIC_VIEW_PREFIX = "topic:view:"
TOPIC_RENAME_PREFIX = "topic:rename:"
COLLECTION_VIEW_PREFIX = "collection:view:"
